# Generated by Django 3.2.5 on 2022-01-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unidade', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('tipo_despesa', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('vencimento_fatura', models.DateField()),
                ('status_pagamento', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'despesas',
            },
        ),
    ]
