# Generated by Django 3.2.5 on 2022-01-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(max_length=50)),
                ('condominio', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unidades',
            },
        ),
    ]
